AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Squiddy serverless .NET API

Resources:
  SquiddyApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/Squiddy.Serverless/
      Handler: Squiddy.Serverless::Squiddy.Serverless.Function::FunctionHandler
      Runtime: dotnet8
      MemorySize: 256
      Timeout: 30
      Architectures:
        - x86_64
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
